cleanup
Signed-off-by: Amir Malka <amirm@armosec.io>

diff --git a/.github/workflows/component-tests.yaml b/.github/workflows/component-tests.yaml
--- a/.github/workflows/component-tests.yaml
+++ b/.github/workflows/component-tests.yaml
@@ -131,16 +131,15 @@ jobs:
             body: comment
           });
 
-    # - name: Cleanup
-    #   if: always()
-    #   run: |
-    #     # If it is a kind cluster, delete it
-    #     if [ -f kind ]; then
-    #       ./kind delete cluster
-    #     else
-    #       helm uninstall kubescape -n kubescape || echo "Failed to uninstall kubecop"
-    #       kubectl delete ns kubescape || echo "Failed to delete namespace kubescape"
-    #       kubectl delete -f ./chart/kubecop/crds/app-profile.crd.yaml -f ./chart/kubecop/charts/clustered-crds/crds/runtime-rule-binding.crd.yaml || echo "Failed to delete crd"
-    #       helm uninstall prometheus -n monitoring || echo "Failed to uninstall prometheus"
-    #       kubectl delete ns monitoring || echo "Failed to delete namespace monitoring"
-    #     fi
+    - name: Cleanup
+      if: always()
+      run: |
+        # If it is a kind cluster, delete it
+        if [ -f kind ]; then
+          ./kind delete cluster
+        else
+          helm uninstall kubescape -n kubescape || echo "Failed to uninstall node agent"
+          kubectl delete ns kubescape || echo "Failed to delete namespace kubescape"
+          helm uninstall prometheus -n monitoring || echo "Failed to uninstall prometheus"
+          kubectl delete ns monitoring || echo "Failed to delete namespace monitoring"
+        fi
